solve : 사칙연산
AlgorithmWarriors/3M500 pull request #9
Opened 2021-01-07 13:32 UTC by ChUngHEe0227

문제 출처: https://programmers.co.kr/learn/courses/30/lessons/1843
참고: https://real-012.tistory.com/62

ps: 어려웠음 시간 두고 천천히 봐 그냥 다음 문제로 이거 풀면서 참고로 코드 리뷰해도 될정도

2021-01-10 09:57 UTC, ByeongjaeJeon requested changes
사칙 연산 코드를 읽어보려 했으나 전혀 눈에 들어오지 않아서 -1 일 때 +라 더하고 -2 일 때는 -라 빼고 대소 비교해서 tmax, tmin 넣는 거 말고는 뭐하는 건지 모르겠어요 선생님 
3차원 배열의 각 축이 뭔지 왜 그렇게 했는지 마지막에 tmax tmin 어디다 넣어서 어떻게 답 내는 건지 등등

2021-01-10 09:57 UTC, ByeongjaeJeon commented on CH_Python/Operations.py
> +            min_n = 9999999
어떤 기준으로 정한 숫자죠?

2021-01-10 09:57 UTC, ByeongjaeJeon commented on CH_Python/Operations.py
> +        for j in range(0,len(arr)-i,2):
i,j라니 못해도 3차원 배열이니 x,y,z 정도로라도 해주시죠

2021-01-10 13:18 UTC, ChUngHEe0227 commented on CH_Python/Operations.py
> +            min_n = 9999999
맥스넘 민넘

2021-01-11 09:44 UTC, ByeongjaeJeon commented on CH_Python/Operations.py
> +            min_n = 9999999
맥스는 1~1000까지 숫자가 2~101개 들어가니까 101000아닌가요

2021-01-11 14:39 UTC, ChUngHEe0227 commented on CH_Python/Operations.py
> +        for j in range(0,len(arr)-i,2):
XYZ 랑 IJK 중 뭐가 나은지 는 의미 없는거 같에

2021-01-11 14:49 UTC, ChUngHEe0227 commented on CH_Python/Operations.py
> +            min_n = 9999999
주석 처리 함

2021-01-11 15:04 UTC, ByeongjaeJeon commented on CH_Python/Operations.py
> +        for j in range(0,len(arr)-i,2):
풀어보니 그런 듯

2021-01-13 13:07 UTC, ByeongjaeJeon approved these changes
와! 드디어 approve!
푼 문제들은 저도 풀어볼게유 고생했으

2021-01-13 13:08 UTC, merged